---
version: "3.9"
services:
  myapp:
    # image: andreyasoskovwork/cat-app:0.1.14
    build: .
    volumes:
      - ./data/mysql-user-name:/run/secrets/mysql-user-name
      - ./data/mysql-user-password:/run/secrets/mysql-user-password
    environment:
      DB_NAME: db1
      DB_HOST: db
      DB_PORT: 3306
    links:
      - "db:DB_HOST"
    ports:
      - 3000:3000
    networks:
      - backend
      - frontend
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test:
        - "CMD"
        - "curl"
        - "-f"
        - "http://localhost:3000/health"
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:10.9.3
    volumes:
      - ./data/mysql-root-password:/run/secrets/mysql-root-password
      - ./data/mysql-user-name:/run/secrets/mysql-user-name
      - ./data/mysql-user-password:/run/secrets/mysql-user-password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
      MYSQL_DATABASE: db1
      MYSQL_USER_FILE: /run/secrets/mysql-user-name
      MYSQL_PASSWORD_FILE: /run/secrets/mysql-user-password
    expose:
      - "3306"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test:
        - "CMD-SHELL"
        - /bin/bash
        - -c
        - mysql -v -b -u "root" -p"$$(cat /run/secrets/mysql-root-password)" -e "SHOW databases;"
      interval: 3s
      retries: 3
      start_period: 5s
      timeout: 2s

networks:
  frontend:
    internal: false
  backend:
    internal: true
