---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "app.fullname" . }}-params"
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ .Values.db_config.db_service }}"
  DB_PORT: "{{ .Values.db_config.db_port }}"
  DB_NAME: "{{ .Values.db_config.db_name }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "app.fullname" . }}-test-scripts"
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  test_app.sh: |
    set -ex

    ### Tests
    # Create
    curl -X GET  http://${APP_HOST}:${APP_PORT}/create

    # Root
    curl -X GET  http://${APP_HOST}:${APP_PORT}/

    # Health
    curl -X GET  http://${APP_HOST}:${APP_PORT}/health

    # Metrics
    curl -X GET  http://${APP_HOST}:${APP_PORT}/metrics

    # Crash
    curl -X GET  http://${APP_HOST}:${APP_PORT}/crash
