---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  generation: 1
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
      app.kubernetes.io/instance: app
    # {{- include "app.selectorLabels" . | nindent 4 }}
