---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "app.fullname" . }}-creds"
  labels:
    {{- include "app.labels" . | nindent 4 }}
stringData:
  mysql-user-name: "{{ .Values.db_config.db_user }}"
  mysql-user-password: "{{ .Values.db_config.db_password }}"
