---
apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  labels:
    app: db
stringData:
  mysql-root-password: wEAzF#5VLE
  mysql-user-name: dbuser
  mysql-user-password: NY#xU8qfXM
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-params
  labels:
    app: db
data:
  MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
  MYSQL_USER_FILE: /run/secrets/mysql-user-name
  MYSQL_PASSWORD_FILE: /run/secrets/mysql-user-password
  MYSQL_DATABASE: db1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
  annotations:
    checkov.io/skip1: CKV_K8S_37=Minimize the admission of containers with capabilities assigned
    checkov.io/skip2: CKV_K8S_40=Containers should run as a high UID to avoid host conflict
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: db
          image: mariadb:10.9.3
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - name: mariadb
              containerPort: 3306
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 999
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - NET_RAW
                # - ALL
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            exec:
              command:
                - /bin/bash
                - -c
                - 'mysql -v -b -u "root" -p"$(cat /run/secrets/mysql-root-password)" "${MYSQL_DATABASE}"  -e "SHOW databases;"'
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            exec:
              command:
                - /bin/bash
                - -c
                - 'mysql -v -b -u "root" -p"$(cat /run/secrets/mysql-root-password)" "${MYSQL_DATABASE}" -e "SHOW databases;"'
          envFrom:
            - configMapRef:
                name: db-params
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
            - name: db-run
              mountPath: /run/mysqld
            - name: tmp
              mountPath: /tmp
            - name: db-creds
              mountPath: "/run/secrets"
              readOnly: true
      volumes:
        - name: db-data
          emptyDir: {}
        - name: db-run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: db-creds
          secret:
            secretName: db-creds
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  ports:
    - name: mariadb
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: db
  type: ClusterIP
