---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-params
  labels:
    app: test
data:
  APP_HOST: "app"
  APP_PORT: "3000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-script
  labels:
    app: test
data:
  test_app.sh: |
    set -ex

    ### Tests
    # Create
    curl -X GET  http://${APP_HOST}:${APP_PORT}/create

    # Root
    curl -X GET  http://${APP_HOST}:${APP_PORT}/

    # Health
    curl -X GET  http://${APP_HOST}:${APP_PORT}/health

    # Metrics
    curl -X GET  http://${APP_HOST}:${APP_PORT}/metrics

    # Crash
    curl -X GET  http://${APP_HOST}:${APP_PORT}/crash

---
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  labels:
    app: test
spec:
  completions: 1
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: test
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: test
          image: alpine/curl:3.14
          command:
            - /bin/sh
          args:
            - /root/test_app.sh
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: test-params
          volumeMounts:
            - name: test-script
              mountPath: /root
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - NET_RAW
                - ALL
      volumes:
        - name: test-script
          configMap:
            name: test-script
            defaultMode: 0444
      restartPolicy: Never
