---
schemaVersion: 2.0.0
commandTests:
  - name: "python test"
    command: "python"
    args: ["--version"]
    expectedOutput: ["Python 3.9.14"]
  - name: "gunicorn flask test"
    command: "which"
    args: ["gunicorn"]
    expectedOutput: ["/usr/local/bin/gunicorn"]
  - name: "curl test"
    command: "curl"
    args: ["--version"]
    exitCode: 0
fileExistenceTests:
  - name: 'Root'
    path: '/usr/src/app/app.py'
    shouldExist: true
    permissions: '-rw-r--r--'
    uid: 0
    gid: 0
metadataTest:
  labels:
    - key: 'version'
      value: '^.*$'
      isRegex: true
    - key: 'description'
      value: '^.*$'
      isRegex: true
  exposedPorts: ["3000"]
  cmd: ["--bind", "0.0.0.0:3000", "--access-logfile", "-", "--error-logfile", "-", "wsgi:app"]
  workdir: "/usr/src/app"
  user: "appuser"
