---
name: Docker-compose
on:
  pull_request:
    branches:
      - "**"
    types:
      - opened
      - edited
      - reopened
    paths:
      - .github/workflows/DC-test.yml
      - app/**
      - data/**
      - .dockerignore
      - Dockerfile
      - .hadolint.yaml
      - docker-compose.yaml

  push:
    branches:
      - "**"
    paths:
      - .github/workflows/DC-test.yml
      - app/**
      - data/**
      - .dockerignore
      - Dockerfile
      - .hadolint.yaml
      - docker-compose.yaml

jobs:
  docker-compose-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run hadolint
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: ./Dockerfile
          config: ./.hadolint.yaml
      - name: Docker-compose check
        run: |
          set -x
          export PATH=$PATH:/usr/libexec/docker/cli-plugins/
          docker-compose -f docker-compose.yaml config
      - name: Run Docker-compose
        run: |
          set -x
          export PATH=$PATH:/usr/libexec/docker/cli-plugins/
          docker-compose -f ./docker-compose.yaml up -d --build
          sleep 20
          docker-compose ps
          docker-compose ps | grep app | grep -i -E 'running|up'
          if [ "$?" = "0" ]; then
            echo "docker-compose OK"
            exit 0
          else
            echo "docker-compose failed"
            exit 1
          fi
          docker-compose down
