---
name: Helm
on:
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - edited
      - reopened
    paths:
      - .github/workflows/Helm.yml
      - Helm/**
  push:
    branches:
      - "**"
    paths:
      - .github/workflows/Helm.yml
      - Helm/**

jobs:
  helm-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.2'
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1
      - name: helm-validate
        run: |
          ct lint --config ./Helm/ct-lint.yaml \
          --charts ./Helm/charts/app
          helm lint ./Helm/charts/app
          helm template app \
          ./Helm/charts/app --values ./Helm/app_values.yaml \
          --validate

          helm install app \
          ./Helm/charts/app --values ./Helm/app_values.yaml \
          --dry-run

      - name: helm-deploy-db
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

          helm template --namespace helm-charts db \
          bitnami/mariadb --version 11.3.3 --values ./Helm/mariadb_values.yaml \
          --validate

          helm install --namespace helm-charts db \
          bitnami/mariadb --version 11.3.3 --values ./Helm/mariadb_values.yaml \
          --dry-run

          helm install --create-namespace --namespace helm-charts db \
          bitnami/mariadb --version 11.3.3 --values ./Helm/mariadb_values.yaml \
          --wait
          sleep 180

      - name: helm-deploy-app
        run: |
          kubectl -n helm-charts get pods
          helm install --create-namespace --namespace helm-charts app \
          ./Helm/charts/app --values ./Helm/app_values.yaml \
          --wait
          # sleep 180
          helm list --namespace helm-charts
          kubectl -n helm-charts get pods

  helm-package:
    runs-on: ubuntu-22.04
    needs: helm-test
    steps:
      - uses: actions/checkout@v3
      - name: Get short-sha
        id: short-sha
        run: |
          SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_ENV
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: Helm Package
        run: helm package ./Helm/charts/app/ -d ./docs/Package
      - uses: actions/upload-artifact@main
        with:
          name: "helm-chart-${{ env.short_sha }}.tgz"
          path: docs/Package
          retention-days: 5
